config/routes.rb
Rails.application.routes.draw do
 resources :instances, except: :show
 devise_for :users, :skip => [:sessions,:registrations,:confirmations]
 as :user do
    get "/login" => "sessions#new", :as => :new_user_session
    post "/login" => "sessions#create", :as => :user_session
    get "/logout" => "sessions#destroy"
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get '/register' => "devise/registrations#new", :as =>:new_user_registration
    get '/deleteaccount' => "devise/registrations#cancel", :as => :cancel_user_registration
    post '/register' => "devise/registrations#create", :as => :user_registration
    get '/account/edit' => "devise/registrations#edit", :as => :edit_user_registration
    patch '/account' => "devise/registrations#update"
    put '/account' => "devise/registrations#update"
    delete '/account' => "devise/registrations#destroy"
    post '/account/confirm' => "devise/confirmations#create", :as => :user_confirmation
    get '/account/confirm/new' => "devise/confirmations#new", :as => :new_user_confirmation
    get '/account/confirm' => "devise/confirmations#show"
  end
  get '/' => 'home#index'
  post '/instances' => 'instances#index'
  get '/instances/' => 'instances#index'
  get '/api/get/instances' => 'instances#update_instance'
  get '/instance/new' => "instances#new"
  post '/instance/new' => "instances#create"
  delete '/instances/' => "instances#destroy"

  post "/hooks" => "instances#hook"

  post '/instances/restart' => "instances#restart", :as => :restart_instance
  post '/instances/start' => "instances#start", :as => :start_instance
  post '/instances/shutdown' => "instances#shutdown",:as => :shutdown_instance
  post '/instance/renew' => "instances#renew_post",:as => :renew_post_instance
  put '/instance/renew' => "instances#renew_put",:as => :renew_put_instance
  post '/instances/resize' => "instances#resize",:as => :resize_instance
  post '/instances/resize_process' => "instances#resize_process",:as => :resize_process_instance
  get '/instances/resize_process/' => redirect('/instances/')

  get '/instance/renew' => redirect('/instances/')
  get '/instance/' => redirect('/instances/')

  get '/support/' => redirect('/support/tickets/')
  get '/support/tickets/' => "tickets#index", :status => "open",:as => :view_tickets
  get '/support/tickets/:status' => "tickets#index"
  get '/support/ticket/:ticketid' => "tickets#index",:as => :ticket
  put '/support/ticket/:ticketid' => "tickets#addreply"
  post '/support/tickets/create' => "tickets#create"
  get '/help/:name' => "pages#help"
  get '/help/' => redirect('/help/introduction')
  get '/legal/:name' => "pages#subpage",:page => "legal"
  get '/legal/' => redirect('/legal/terms')
  get '/pricing' => "pages#page", :name => "pricing"
  get '/features' => "pages#page", :name => "features"
  get '/contact' => "pages#page", :name => "contact"
  get '/domains' => "records#index",:as => :domains
  post '/domains' => "records#create"
  get '/domain/:domainname' => "records#view_domain",:as => :view_domain,:domainname => /[^\/]+/
  delete 'delete/domain/:domainname' => "records#delete_domain",:as => :delete_domain,:domainname=> /[^\/]+/
  post '/domain/:domainname/' => "records#add_record",as: :add_record,:domainname => /[^\/]+/
  put '/domain/:domainname/' => "records#update_record",as: :update_record,:domainname => /[^\/]+/
  delete '/delete/:domainname/record/:id' => "records#delete_record",as: :delete_record,:domainname => /[^\/]+/

  get '/admin' => "admin#index"
  get '/admin/index' => "admin#index"
  get '/admin/instances' => "admin#instances"
  get '/admin/tickets' => "admin#tickets"
  get '/admin/ticket/:ticketid' => "admin#tickets"
  get '/admin/users' => "admin#users"
  root 'home#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :user
  scope :createdby,-> {order('created_at DESC')}
  def paypal_url(inst)
    if inst.temp_status.nil?
      if inst.duration == 1
        if inst.size == "512mb"
          price = '6'
        elsif inst.size == '1gb'
          price = '11'
        elsif inst.size == '2gb'
          price = '22'
        end
      elsif inst.duration == 3
        if inst.size == "512mb"
          if inst.user.had_instance  
            price = '15.99'
          else
            price ='12'
          end
        elsif inst.size == '1gb'
          price = '28.99'
        elsif inst.size == '2gb'
          price = '57.99'
        end
      elsif inst.duration == 6
        if inst.size == "512mb"
          if inst.user.had_instance  
            price = '31.99'
          else
            price = '30'
          end
        elsif inst.size == '1gb'
          price = '59.99'
        elsif inst.size == '2gb'
          price = '121.99'
        end
      end
    elsif inst.temp_status == "Renewing" || inst.temp_status == "Resizing"
      if inst.size == "512mb"
        price = 6 * duration
      elsif inst.size == '1gb'
        price = 11 * duration
      else
        price = 22 * duration
      end
    end
    if inst.duration == 1
      month = "Month"
    else
      month = "Months"
    end
    inst.update_attributes(price: price)
    values = {
        business: "support@lideploy.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}/instances/",
        invoice: "#{inst.name.upcase}#{inst.id}LIDEPLOY#{Time.now}",
        custom: inst.size,
        amount: price,
        item_name: "#{inst.size.upcase} Server for #{inst.duration} #{month} on Lideploy.com",
        item_number: inst.id,
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/hooks"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
	before_action :authenticate_user!,:except => [:hook]
	#Allocate a new Instance model
	def new
		@newinstance = Instance.new
	end
	#Create a new Instance from Form Input
	def create
		createinstance= current_user.instances.new(instance_params)
		createinstance.status = 'Waiting for Payment Confirmation'
		if createinstance.save
			#Free for 1st instance most basic plan
			if !current_user.had_instance && createinstance.size == "512mb" && createinstance.duration == 1
				begin
					current_do_key = ENV["DO_SECRET_KEY"]
					client = DropletKit::Client.new(access_token: current_do_key)
					droplet = DropletKit::Droplet.new(name: createinstance.name,region: createinstance.region,size: createinstance.size,image: createinstance.image)
					created = client.droplets.create(droplet)
					current_user.update_attributes(had_instance: true)
					createinstance.update_attributes(:instanceid => created.id,:status => created.status,:api_key => current_do_key,:expires => Time.now+ createinstance.duration.months,purchased_at: Time.now)
				rescue
					createinstance.update_attributes(status: "Error creating Instance")
				end
				redirect_to instances_path
			else
				redirect_to createinstance.paypal_url(createinstance)
			end
		end
	end
	#List all Instances of A Particular User
	def index
		@instances = current_user.instances.createdby
	end
	#Start an Instance
	def start
		instance = current_user.instances.find(params[:id])
		begin
			client = DropletKit::Client.new(access_token: instance.api_key)
			droplet = client.droplet_actions.power_on(droplet_id: instance.instanceid)
			instance.update_attributes(:status => "Starting")
			flash[:notice] = "Instance Started"
		rescue
			flash[:alert] = "Error Occurred while Starting Instance.Try again after few minutes."
		end
		instance = nil
		redirect_to instances_path
	end
	#Delete an Instance
	def destroy
	  instance = current_user.instances.find(params[:id])
		begin
			client = DropletKit::Client.new(access_token: instance.api_key)
			client.droplets.delete(id: instance.instanceid)
			flash[:notice] = "Instance Deleted Successfully"
		rescue
			flash[:alert] = "Instance Deleted Successfully"
		end
		instance.destroy
		instance = nil
		redirect_to instances_path
	end
	#Restart an Instance
	def restart
		instance = current_user.instances.find(params[:id])
		begin
			client = DropletKit::Client.new(access_token: instance.api_key)
			client.droplet_actions.reboot(droplet_id: instance.instanceid)
			instance.update_attributes(:status => "Restarting")
			flash[:notice] = "Restarted Successfully"
		rescue
			flash[:alert] = "Error Occurred While Restarting. Try again after few minutes."
		end
		instance = nil
		redirect_to instances_path
	end
	#Power off an Instance
	def shutdown
		instance = current_user.instances.find(params[:id])
		begin
			client = DropletKit::Client.new(access_token: instance.api_key)
			shuttingdown = client.droplet_actions.shutdown(droplet_id: instance.instanceid)
			instance.update_attributes(:status => "Shutting Down",:action => shuttingdown.id)
			flash[:notice] = "Shutdown Initiated.It will be completed within few seconds."
		rescue
			flash[:alert] = "Trying to shutdown.Try again in few minutes if Instance is still active."
		end
		instance = nil
		redirect_to instances_path
	end
	#Renew Instance(Render Page part)
	def renew_put
			@instance = current_user.instances.find(params[:id])
			render 'renew'
	end
	#Renew Instance(Process Payment and redirect to payment processor)
	def renew_post
		begin
			instance = current_user.instances.find(params[:id])
			raise "Not Found" if instance.nil?
			redirect_to instance.paypal_url(instance)	if instance.update_attributes(:duration => params[:instance][:duration],:temp_status => "Renewing")
		rescue
			flash[:alert] = "Instance Not Found"
			redirect_to instances_path
		end
	end
	#Resize an Instance
	def resize
		begin
			@instance = current_user.instances.find(params[:id])
			raise "Not Found" if @instance.nil?
			if @instance.status != "Powered Off" && @instance.size != "2gb"
				flash[:notice1] = "Try resizing when instance is Powered Off"
				shutdown
			end
		rescue
			flash[:notice] = "Instance Not Found or Unknown State"
			redirect_to instances_path and return
		end
	end
	#Resize - Process Resizing - Redirect to Paypal
	def resize_process
		instance = current_user.instances.find(params[:id])
		instance.update_attributes(:temp_status => "Resizing",:duration => params[:instance][:duration])
		instance.size=params[:instance][:size]
		redirect_to instance.paypal_url(instance)
	end
	#Update Instance status
	def update_instance
		inst = current_user.instances.find(params[:id])
		@vinst = inst
		begin
			tries = 0
			client = DropletKit::Client.new(access_token: inst.api_key)
			if !inst.action.nil?
				actionstatus = client.actions.find(id:inst.action).status
			end
			begin
				instance = client.droplets.find(id: inst.instanceid)
				if instance.status == 'off'
					if inst.status == 'active' || inst.status == 'Not Found'
						status = 'Powered Off'
					elsif inst.status == 'Shutting Down'
						status = 'Powered Off'
						inst.update_attributes(action: nil)
					else
						status = inst.status
					end
				elsif inst.status == 'Shutting Down' && (actionstatus == 'in-progress' || actionstatus == 'completed')
					status = inst.status
				else
					status = instance.status
				end
				inst.update_attributes(ip_address: instance.networks.v4[0].ip_address,vcpus: instance.vcpus,disk: instance.disk,status: status)
				if inst.temp_status == "Renewed"
					flash.now[:notice] = "Renewed Successfully"
					inst.update_attributes(temp_status: nil)
				elsif inst.temp_status == "Resized"
					if inst.status == 'Resizing' && (actionstatus == "completed")
						client.droplet_actions.power_on(droplet_id: inst.instanceid)
						inst.update_attributes(status: "Starting",temp_status: nil,action: nil)
						flash.now[:notice] = "Resized Successfully"
						flash.now[:notice1] = "Instance Started"
					end
				end
			rescue => e
				if inst.status == "Payment Failed"
					flash.now[:notice] = "Payment Not Completed for #{inst.name}.Please Contact us at support@lideploy.com for further help"
					inst.update_attributes(status: "Payment failed");
				elsif inst.status != 'Waiting for Payment Confirmation' && inst.status != "Payment failed"
					tries += 1
					retry if tries < 2
					inst.update_attributes(status: "Not Found",ip_address: nil,disk: nil)
				end
			end
		rescue => e
			flash.now[:alert] = "An Unknown Error occurred.Please try again later."
		end
		render "instances/shared/update_instance",layout: false
	end

	protect_from_forgery except: [:hook]
	  def hook
	    params.permit! # Permit all Paypal input params
		instance = Instance.find(params[:item_number])
	    if params[:payment_status] == "Completed" && (params[:payment_gross].to_f == (instance.price).to_f)
				if instance.temp_status == "Renewing"
					instance.update_attributes(:temp_status => "Renewed",:expires => instance.expires+instance.duration.months)
				elsif instance.temp_status == "Resizing"
					client = DropletKit::Client.new(access_token: instance.api_key)
					resizing = client.droplet_actions.resize(droplet_id: instance.instanceid,size:params[:custom],disk: true)
					instance.update_attributes(:size => params[:custom],:status => "Resizing",:temp_status => "Resized",:expires => Time.now+instance.duration.months,:action => resizing.id)
				elsif instance.status == "Waiting for Payment Confirmation"
					instance.update_attributes notification_params: params, transaction_id: params[:txn_id], purchased_at: Time.now
					current_do_key = ENV["DO_SECRET_KEY"]
					client = DropletKit::Client.new(access_token: current_do_key)
					droplet = DropletKit::Droplet.new(name: instance.name,region: instance.region,size: instance.size,image: instance.image)
					created = client.droplets.create(droplet)
					instance.user.update_attributes(had_instance: true)
					instance.update_attributes(:instanceid => created.id,:status => created.status,:api_key => current_do_key,:expires => Time.now+instance.duration.months)
				end
			else
				instance.update_attributes(:status=> "Payment Failed")
			end
			instance = nil
	    render nothing: true
	  end

	private
	def instance_params
		params.require(:instance).permit(:name,:distro,:region,:image,:size,:duration)
	end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/index.html.erb
<% title "Instances" %>
<% content_for :head do %>
  <style>
    td .dropdown-menu {
  		width: 100%;
  		padding: 0px;
  		border-left: 5px;
  		border-right: 5px;
  		}
    .modal-title,.modal-body p{
      text-align: center;
      font-family: 'quicksandbold'
    }
		td .dropdown-toggle{
			min-width: 160px;
		}
		td .dropdown-item.btn-primary{
			border: 0px;
			border-radius: 0px;
		}

  	td .dropdown-item.btn,.cancel.btn-default,.destroy.btn{
  		width: 100% !important;
  	}
    td .dropdown-item.destroy.btn{
      max-width:  160px;
    }
    .Active{
      color: #26A65B !important;
    }
    .New,.Starting,.Restarting,.Shuttingdown,.Resizing{
      color: #F57C00 !important;
    }
    .Def{
      font-family: 'quicksandbold' !important;ol;;;;
      color: #ef5350;
    }
    /*tablecss*/
    td{
      padding-top: 15px !important;
      padding-bottom: 15px !important;
      }
    .theader>th{
      text-align: center;
      font-family: 'quicksandbold';
      font-size: 135%;
      color: #535151;
    }
    .trow>td{
      text-align: center;
      font-family: 'quicksandregular';
      font-size: 120%;
      font-weight: 600;
      border: 0 !important;
      vertical-align: middle !important;
    }
    .instname{
      font-family: 'quicksandbold';
      color: #3190e7;
    }
    .instdetails{
      font-family: 'quicksandlight';
      font-size: 80%;
    }
 	</style>
  <script>
    var refreshInstances;
    var autoRefresh;
    var timeouts = [];
    var loadState = true;
    var clearTimeoutsAndInterval = function(){
      clearInterval(autoRefresh);
      for (var i=0; i<timeouts.length; i++) {
        clearTimeout(timeouts[i]);
      }
    }
    $(document).ready(function(){
      var instances = $(".trow");
      var intervalDuration = 15000 * (instances.length);
      refreshInstances = function(offset){
        var timeoutDuration = 0;
        $(instances).each(function(){
          var id=$(this).attr('id');
          if(!$(this).hasClass("loading"))
          {
            $(this).addClass("loading");
            timeouts.push(setTimeout(function() {
              $("#" + id).load('/api/get/instances?id=' + id,function(){
                $('#' + id).removeClass("loading");
              });
            }, timeoutDuration));
            timeoutDuration += offset;
          }
        });
      }
      if(instances.length > 0){
        refreshInstances(1000);
        var autoRefresh = setInterval(function(){refreshInstances(8000)},intervalDuration);
      }
    });
    $(window).unload(function(){
      clearTimeoutsAndInterval();
    });
    $(document).on("turbolinks:click",function(){clearTimeoutsAndInterval();});
    $(document).one('click','.button_to',function(){
      if(loadState){
        loadState = false;
        $.notifyClose();
        $('body').append('<div class="ajax-loading"></div>');
        clearTimeoutsAndInterval();
        loadState = true;
      }
    });
  </script>
<% end %>
<div class="container instancelist feature-box">
  <% if @instances.blank? %>
  	<h1> Create An Instance </h1>
  	<i class="fa fa-server fa-5x"></i>
  	<h2> You don't seem to have any instances </h2>
  	<h3> Create One Now with just a Few Clicks ! </h3>
  	<a class="btn btn-default signupbutton" href="/instances/new/" style="width: 50% !important;" role="button">Create Instance</a>
  <% else %>
  	<table class="table table-sm">
  		<thead>
  			<tr class="theader">
  				<th>Distribution</th>
  				<th>Name</th>
  				<th>IP Address</th>
  				<th>Status</th>
          <th>Expires</th>
  				<th></th>
  			</tr>
  		</thead>
  		<tbody>
  			<% Array(@instances).each do |inst| %>
  				<tr class="trow" id="<%= inst.id %>">
  					<td><img src='<%= image_path("#{inst.distro.downcase}-32.png") %>' alt="<%=inst.distro%>"></td>
  					<td>
              <%if inst.disk? %>
                <span class="instname"><%= inst.name%></span><br/>
                <span class ="instdetails"><%=inst.size.upcase%> Memory / <%= inst.disk%>GB Disk</span>
              <%else%>
                <span class="instname"><%= inst.name%>
              <%end%>
            </td>
  					<td><%= inst.ip_address %></td>
  					<td class="Def <%= inst.status.capitalize.delete(' ') %>">
  						<%if inst.status.capitalize == "New" %>
  							Creating Instance
  						<%else%>
  							<%= inst.status.capitalize %>
  						<%end%>
  					</td>
            <td>
              <% if inst.disk? %>
                <%= inst.expires.strftime('%-d %B %Y') %>
              <%else%>
                <span class="Def">-</span>
              <%end%>
            </td>
            <td>
  					<% if inst.disk? %>
  						<div class="btn-group">
                <% if inst.status == "new" || inst.status == "Resizing" || inst.status == "Shutting Down" || inst.status == "Starting" %>
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" disabled>Action</button>
                <% else %>
  								<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
  								<div class="dropdown-menu">
                    <% if inst.status == "Powered Off" %>
                      <%= button_to "Start",start_instance_path(:id=> inst.id),method: :post,remote: true,:class => "btn btn-primary dropdown-item",:title => "Start Instance" %>
                    <% else %>
                      <%= button_to "Shutdown",shutdown_instance_path(:id=>inst.id),method: :post,remote: true,:class => "btn btn-primary dropdown-item",:title => "Shutdown Instance" %>
                      <%= button_to "Restart",restart_instance_path(:id => inst.id),method: :post,remote: true,:class => "btn btn-primary dropdown-item",:title => "Restart Instance" %>
                    <% end %>
                    <%= link_to "Renew",renew_put_instance_path(:id => inst.id),method: :put,remote: true,:class => "button_to btn btn-primary dropdown-item",:title => "Renew Instance" %>
                    <%= button_to "Resize",resize_instance_path(:id => inst.id),method: :post,remote: true,:class => "btn btn-primary dropdown-item",:titke => "Resize Instance" %>
                    <%= button_to "Destroy",instances_path(:id => inst.id),method: :delete,remote: true,:class => "btn btn-primary destroy dropdown-item",:title => "Destroy this Instance?",data: {:confirm => "This Action is irreversible<br/>Be Certain!"}%>
                  </div>
                <% end %>
  						</div>
              <% else%>
                <% if inst.status != "new" %>
                  <%= button_to "Delete",instances_path(:id => inst.id),method: :delete,remote: true,:class => "btn btn-primary destroy dropdown-item" %>
                <%end%>
            <% end %>
  					</td>
  				</tr>
  			<% end %>
  		</tbody>
  	</table>
  <% end %>
</div>

app/views/instances/renew.html.erb
<% title "Renew Instance" %>
<% content_for :head do%>
  <script>
    var instSize = "<%= @instance.size%>"
    var sizeArr = {"512mb":"low","1gb":"mid","2gb":"high"}
    $(document).ready(function(){
      $('.' + sizeArr[instSize]).show().addClass("active");

      $(".onemonth").on("click",function(){
        $(".renewaldate").text("<%= (@instance.expires+1.month).strftime('%e %B %Y')%>");
      });
      $(".threemonth").on("click",function(){
        $(".renewaldate").text("<%= (@instance.expires+3.month).strftime('%e %B %Y')%>");
      });
      $(".sixmonth").on("click",function(){
        $(".renewaldate").text("<%= (@instance.expires+6.month).strftime('%e %B %Y')%>");
      });

    });
  </script>
  <style>
    .sizes{
      display: none;
    }
  </style>
<%end%>
<div class="container feature-box" style="margin-top:10px;">
  <h1 class="renew header">Renew <%= @instance.name %></h1><br/>
    <div class = "renew details">
      Memory: <%= @instance.size.upcase %><span class="renew header">&nbsp;|&nbsp;</span><img src='<%= image_path("#{@instance.distro.downcase}-32.png")%>' alt="<%=@instance.distro%>"><span class="renew header">&nbsp;|&nbsp;</span>Disk: <%= @instance.disk %>GB<br/>
      Current Expiry Date: <%= @instance.expires.strftime('%-d %B %Y') %><br/>
      Current Plan Expires in : <span class="header"><%= ((@instance.expires - Time.now).to_i/86400)%> Days</span><br/>
      <br/>
    </div>
    <h2 class ="renew header">Current Plan</h2>
    <div class="btn" data-toggle="buttons">
      <div class="btn low sizes">
        <div class="dis prices text">
          <h3><sup>$</sup>6/Month</h3>
        </div>
        <div class="specs">
          <ul>
            <li><span>512 MB</span> RAM</li>
            <li><span>2.4 GHz</span> Single Core CPU</li>
            <li><span>20 GB SSD</span> Disk</li>
            <li><span>1000 GB</span> Transfer</li>
          </ul>
        </div>
      </div>
      <div class="btn mid active sizes">
        <div class="dis prices text">
          <h3><sup>$</sup>11/Month</h3>
        </div>
        <div class="specs">
          <ul>
            <li><span>1 GB</span> RAM</li>
            <li><span>2.4 GHz</span> Single Core CPU</li>
            <li><span>30 GB SSD</span> Disk</li>
            <li><span>2000 GB</span> Transfer</li>
          </ul>
        </div>
      </div>
      <div class="btn high sizes">
        <div class="dis prices text">
          <h3><sup>$</sup>22/Month</h3>
        </div>
        <div class="specs">
          <ul>
            <li><span>2 GB</span> RAM</li>
            <li><span>2.4 GHz</span> Dual Core CPU</li>
            <li><span>40 GB SSD</span> Disk</li>
            <li><span>3000 GB</span> Transfer</li>
          </ul>
        </div>
      </div>
    </div>

    <h2 class="renew header">Select Renew Duration</h2>
    <br>
    <%= simple_form_for(@instance,:url => renew_post_instance_path(id: @instance.id),method: :post, defaults: {label: false,error_html: { class: 'rederror'}},html: { autocomplete: 'off' }) do |f| %>
      <%= f.error_notification %>
      <div class = "duration">
        <div class="btn-group" data-toggle="buttons">
  				<label class="btn btn-primary onemonth">
  					<%= f.radio_button :duration,1,:checked => false %>
  					1 Month
  				</label>
  				<label class="btn btn-primary threemonth active">
  					<%= f.radio_button :duration,3,:checked => true %>
  					3 Months
  				</label>
  				<label class="btn btn-primary sixmonth">
  					<%= f.radio_button :duration,6,:checked => false %>
  					6 Months
  				</label>
  			</div>
        <br/><br/>
        <div class = "renew details">
          After Renewal Expiry Date: <span class="renewaldate"><%= (@instance.expires+3.month).strftime('%-d %B %Y')%></span><br/>
          <br/>
        </div>
  			<div class="form-actions">
  	    	<%= f.button :submit, "Renew Instance", :class => 'signupbutton' %>
  	  	</div>
      </div>
    <% end %>
</div>