config/routes.rb
Rails.application.routes.draw do
 resources :instances, except: :show
 devise_for :users, :skip => [:sessions,:registrations,:confirmations]
 as :user do
    get "/login" => "sessions#new", :as => :new_user_session
    post "/login" => "sessions#create", :as => :user_session
    get "/logout" => "sessions#destroy"
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get '/register' => "devise/registrations#new", :as =>:new_user_registration
    get '/deleteaccount' => "devise/registrations#cancel", :as => :cancel_user_registration
    post '/register' => "devise/registrations#create", :as => :user_registration
    get '/account/edit' => "devise/registrations#edit", :as => :edit_user_registration
    patch '/account' => "devise/registrations#update"
    put '/account' => "devise/registrations#update"
    delete '/account' => "devise/registrations#destroy"
    post '/account/confirm' => "devise/confirmations#create", :as => :user_confirmation
    get '/account/confirm/new' => "devise/confirmations#new", :as => :new_user_confirmation
    get '/account/confirm' => "devise/confirmations#show"
  end
  get '/' => 'home#index'
  post '/instances' => 'instances#index'
  get '/instances/' => 'instances#index'
  get '/api/get/instances' => 'instances#update_instance'
  get '/instance/new' => "instances#new"
  post '/instance/new' => "instances#create"
  delete '/instances/' => "instances#destroy"

  post "/hooks" => "instances#hook"

  post '/instances/restart' => "instances#restart", :as => :restart_instance
  post '/instances/start' => "instances#start", :as => :start_instance
  post '/instances/shutdown' => "instances#shutdown",:as => :shutdown_instance
  post '/instance/renew' => "instances#renew_post",:as => :renew_post_instance
  put '/instance/renew' => "instances#renew_put",:as => :renew_put_instance
  post '/instances/resize' => "instances#resize",:as => :resize_instance
  post '/instances/resize_process' => "instances#resize_process",:as => :resize_process_instance
  get '/instances/resize_process/' => redirect('/instances/')

  get '/instance/renew' => redirect('/instances/')
  get '/instance/' => redirect('/instances/')

  get '/support/' => redirect('/support/tickets/')
  get '/support/tickets/' => "tickets#index", :status => "open",:as => :view_tickets
  get '/support/tickets/:status' => "tickets#index"
  get '/support/ticket/:ticketid' => "tickets#index",:as => :ticket
  put '/support/ticket/:ticketid' => "tickets#addreply"
  post '/support/tickets/create' => "tickets#create"
  get '/help/:name' => "pages#help"
  get '/help/' => redirect('/help/introduction')
  get '/legal/:name' => "pages#subpage",:page => "legal"
  get '/legal/' => redirect('/legal/terms')
  get '/pricing' => "pages#page", :name => "pricing"
  get '/features' => "pages#page", :name => "features"
  get '/contact' => "pages#page", :name => "contact"
  get '/domains' => "records#index",:as => :domains
  post '/domains' => "records#create"
  get '/domain/:domainname' => "records#view_domain",:as => :view_domain,:domainname => /[^\/]+/
  delete 'delete/domain/:domainname' => "records#delete_domain",:as => :delete_domain,:domainname=> /[^\/]+/
  post '/domain/:domainname/' => "records#add_record",as: :add_record,:domainname => /[^\/]+/
  put '/domain/:domainname/' => "records#update_record",as: :update_record,:domainname => /[^\/]+/
  delete '/delete/:domainname/record/:id' => "records#delete_record",as: :delete_record,:domainname => /[^\/]+/

  get '/admin' => "admin#index"
  get '/admin/index' => "admin#index"
  get '/admin/instances' => "admin#instances"
  get '/admin/tickets' => "admin#tickets"
  get '/admin/ticket/:ticketid' => "admin#tickets"
  get '/admin/users' => "admin#users"
  root 'home#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :domain
  scope :alphabetically,-> {order('record_type ASC')}
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @domains = current_user.domains.recent
    @newdomain = Domain.new
    @instances = current_user.instances
  end
  def create
    newdomain = current_user.domains.new(domain_params)
    begin
      newdomain.api_key = ENV["DO_SECRET_KEY"]
      client = DropletKit::Client.new(access_token: newdomain.api_key)
      domain = DropletKit::Domain.new(name: newdomain.name, ip_address: newdomain.ip_address)
      client.domains.create(domain)
      default_record = (client.domain_records.all(for_domain: newdomain.name).to_a)[-1]
      newdomain.save
      newdomain.records.create(record_type:'A',name:'@',data: newdomain.ip_address,record_id: default_record.id)
      flash[:notice] = "Domain Record Created."
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        if $1.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = $1
        end
      end
      flash[:alert] = "Failed to create Domain Record. #{exception_message}"
    end
    newdomain,default_record,domain,exception_message = nil
    redirect_to domains_path
  end

  def view_domain
    @domain = current_user.domains.find_by_name(params[:domainname])
    @records = @domain.records.alphabetically
    @newrecord = @domain.records.new
    render 'records/domain'
  end

  def delete_domain
    domain = current_user.domains.find_by_name(params[:domainname])
    tries = 0
    begin
      client = DropletKit::Client.new(access_token:domain.api_key)
      client.domains.delete(name:domain.name)
      flash[:notice] = "Domain #{domain.name} deleted successfully."
    rescue
      tries += 1
      retry if tries < 2
      flash[:alert] = "Domain Deleted"
    end
    domain.destroy
    domain = nil
    redirect_to domains_path
  end

  def add_record
    domain = current_user.domains.find_by_name(params[:domainname])
    begin
      client = DropletKit::Client.new(access_token:domain.api_key)
      newrecord = DropletKit::DomainRecord.new(type: params[:record][:record_type], name: params[:record][:name], data: params[:record][:data],port: params[:record][:port],weight: params[:record][:weight],priority: params[:record][:priority])
      crecord = client.domain_records.create(newrecord, for_domain: params[:domainname])
      if !crecord.id.nil?
        record = domain.records.create(record_type: crecord.type,name: crecord.name,data: crecord.data,port:crecord.port,weight:crecord.weight,priority: crecord.priority,record_id: crecord.id)
        flash[:notice] = "Record Created Successfully"
      else
        flash[:alert] = "Error Occured while saving record"
      end
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        err = $1
        if err.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = err
        end
      end
      flash[:alert] = "Error Occurred while creating Domain Record. #{exception_message}"
    end
    record,crecord,err,exception_message,client = nil
    redirect_to view_domain_path
  end
  def update_record
    begin
      domain = current_user.domains.find_by_name(params[:domainname])
      record = domain.records.find(params[:record][:id])
      client = DropletKit::Client.new(access_token:domain.api_key)
      updaterecord = DropletKit::DomainRecord.new(type: params[:record][:record_type], name: params[:record][:name], data: params[:record][:data],port: params[:record][:port],weight: params[:record][:weight],priority: params[:record][:priority])
      crecord = client.domain_records.update(updaterecord, for_domain: params[:domainname], id: record.record_id)
      record.update_attributes(name: crecord.name,data: crecord.data,port:crecord.port,weight:crecord.weight,priority: crecord.priority)
      flash[:notice] = "Record Updated"
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        if $1.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = $1
        end
      end
      flash[:alert] = "Error occured while updating record. #{exception_message}"
    end
    record,client,updaterecord,crecord,exception_message = nil
    redirect_to view_domain_path
  end

  def delete_record
    begin
      domain = current_user.domains.find_by_name(params[:domainname])
      record = domain.records.find(params[:id])
      client = DropletKit::Client.new(access_token:domain.api_key)
      client.domain_records.delete(for_domain: domain.name, id: record.record_id)
      flash[:notice] = "Record Deleted"
    rescue
      flash[:alert] = "Record Deleted"
    end
    record.destroy
    record,client = nil
    redirect_to view_domain_path
  end
  private
  def domain_params
    params.require(:domain).permit(:name,:ip_address)
  end
  def record_params
   params.require(:record).permit(:record_type,:name,:data,:priority,:port,:weight)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/shared/_a.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12 update-record"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :name,placeholder: "Name",class: "record name"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "IP Address",class: "record data"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
<% end %>

app/views/records/shared/_aaaa.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12 update-record"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :name,placeholder: "Name",class: "record name"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "IPv6 Address",class: "record data"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
<% end %>

app/views/records/shared/_cname.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12 update-record"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :name,placeholder: "Name",class: "record name"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "Points to",class: "record data"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
<% end %>

app/views/records/shared/_mx.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "update-record col-md-12"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "Hostname",class: "record data"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :priority,placeholder: "Priority",class: "record priority"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
<% end %>

app/views/records/shared/_srv.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12 update-record"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :name,placeholder: "Name",class: "record name"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "Hostname",class: "record data"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "srv-button update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <%= f.input_field :priority,placeholder: "Priority",class: "record priority"%>
    </div>
    <div class="col-md-2">
      <%= f.input_field :port,placeholder: "Port",class: "record port"%>
    </div>
    <div class="col-md-2">
      <%= f.input_field :weight,placeholder: "Weight",class: "record weight"%>
    </div>

  </div>
<% end %>

app/views/records/shared/_txt.html.erb
<%= simple_form_for(record,:url => update_record_path,method: :put,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12 update-record"}) do |f| %>
  <%= f.hidden_field :id,value: record.id %>
  <div class="row">
    <div class="col-md-2">
      <label class="record-type active <%=record.record_type.downcase%>">
        <%= record.record_type %>
      </label>
    </div>
    <div class="col-md-3">
      <%= f.input_field :name,placeholder: "Name",class: "record name"%>
    </div>
    <div class="col-md-3">
      <%= f.input_field :data,placeholder: "Text",class: "record data"%>
    </div>
    <div class="col-md-2">
      <%= f.button :submit, "Update",class: "update-record-button inactive"%>
    </div>
    <div class="col-md-2">
      <%= link_to "Delete",delete_record_path(:domainname=> record.domain.name,:id => record.id),method: :delete,:class => "btn btn-default delete-record-button"%>
    </div>
  </div>
<% end %>