config/routes.rb
Rails.application.routes.draw do
 resources :instances, except: :show
 devise_for :users, :skip => [:sessions,:registrations,:confirmations]
 as :user do
    get "/login" => "sessions#new", :as => :new_user_session
    post "/login" => "sessions#create", :as => :user_session
    get "/logout" => "sessions#destroy"
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
    get '/register' => "devise/registrations#new", :as =>:new_user_registration
    get '/deleteaccount' => "devise/registrations#cancel", :as => :cancel_user_registration
    post '/register' => "devise/registrations#create", :as => :user_registration
    get '/account/edit' => "devise/registrations#edit", :as => :edit_user_registration
    patch '/account' => "devise/registrations#update"
    put '/account' => "devise/registrations#update"
    delete '/account' => "devise/registrations#destroy"
    post '/account/confirm' => "devise/confirmations#create", :as => :user_confirmation
    get '/account/confirm/new' => "devise/confirmations#new", :as => :new_user_confirmation
    get '/account/confirm' => "devise/confirmations#show"
  end
  get '/' => 'home#index'
  post '/instances' => 'instances#index'
  get '/instances/' => 'instances#index'
  get '/api/get/instances' => 'instances#update_instance'
  get '/instance/new' => "instances#new"
  post '/instance/new' => "instances#create"
  delete '/instances/' => "instances#destroy"

  post "/hooks" => "instances#hook"

  post '/instances/restart' => "instances#restart", :as => :restart_instance
  post '/instances/start' => "instances#start", :as => :start_instance
  post '/instances/shutdown' => "instances#shutdown",:as => :shutdown_instance
  post '/instance/renew' => "instances#renew_post",:as => :renew_post_instance
  put '/instance/renew' => "instances#renew_put",:as => :renew_put_instance
  post '/instances/resize' => "instances#resize",:as => :resize_instance
  post '/instances/resize_process' => "instances#resize_process",:as => :resize_process_instance
  get '/instances/resize_process/' => redirect('/instances/')

  get '/instance/renew' => redirect('/instances/')
  get '/instance/' => redirect('/instances/')

  get '/support/' => redirect('/support/tickets/')
  get '/support/tickets/' => "tickets#index", :status => "open",:as => :view_tickets
  get '/support/tickets/:status' => "tickets#index"
  get '/support/ticket/:ticketid' => "tickets#index",:as => :ticket
  put '/support/ticket/:ticketid' => "tickets#addreply"
  post '/support/tickets/create' => "tickets#create"
  get '/help/:name' => "pages#help"
  get '/help/' => redirect('/help/introduction')
  get '/legal/:name' => "pages#subpage",:page => "legal"
  get '/legal/' => redirect('/legal/terms')
  get '/pricing' => "pages#page", :name => "pricing"
  get '/features' => "pages#page", :name => "features"
  get '/contact' => "pages#page", :name => "contact"
  get '/domains' => "records#index",:as => :domains
  post '/domains' => "records#create"
  get '/domain/:domainname' => "records#view_domain",:as => :view_domain,:domainname => /[^\/]+/
  delete 'delete/domain/:domainname' => "records#delete_domain",:as => :delete_domain,:domainname=> /[^\/]+/
  post '/domain/:domainname/' => "records#add_record",as: :add_record,:domainname => /[^\/]+/
  put '/domain/:domainname/' => "records#update_record",as: :update_record,:domainname => /[^\/]+/
  delete '/delete/:domainname/record/:id' => "records#delete_record",as: :delete_record,:domainname => /[^\/]+/

  get '/admin' => "admin#index"
  get '/admin/index' => "admin#index"
  get '/admin/instances' => "admin#instances"
  get '/admin/tickets' => "admin#tickets"
  get '/admin/ticket/:ticketid' => "admin#tickets"
  get '/admin/users' => "admin#users"
  root 'home#index'

end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :domain
  scope :alphabetically,-> {order('record_type ASC')}
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def index
    @domains = current_user.domains.recent
    @newdomain = Domain.new
    @instances = current_user.instances
  end
  def create
    newdomain = current_user.domains.new(domain_params)
    begin
      newdomain.api_key = ENV["DO_SECRET_KEY"]
      client = DropletKit::Client.new(access_token: newdomain.api_key)
      domain = DropletKit::Domain.new(name: newdomain.name, ip_address: newdomain.ip_address)
      client.domains.create(domain)
      default_record = (client.domain_records.all(for_domain: newdomain.name).to_a)[-1]
      newdomain.save
      newdomain.records.create(record_type:'A',name:'@',data: newdomain.ip_address,record_id: default_record.id)
      flash[:notice] = "Domain Record Created."
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        if $1.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = $1
        end
      end
      flash[:alert] = "Failed to create Domain Record. #{exception_message}"
    end
    newdomain,default_record,domain,exception_message = nil
    redirect_to domains_path
  end

  def view_domain
    @domain = current_user.domains.find_by_name(params[:domainname])
    @records = @domain.records.alphabetically
    @newrecord = @domain.records.new
    render 'records/domain'
  end

  def delete_domain
    domain = current_user.domains.find_by_name(params[:domainname])
    tries = 0
    begin
      client = DropletKit::Client.new(access_token:domain.api_key)
      client.domains.delete(name:domain.name)
      flash[:notice] = "Domain #{domain.name} deleted successfully."
    rescue
      tries += 1
      retry if tries < 2
      flash[:alert] = "Domain Deleted"
    end
    domain.destroy
    domain = nil
    redirect_to domains_path
  end

  def add_record
    domain = current_user.domains.find_by_name(params[:domainname])
    begin
      client = DropletKit::Client.new(access_token:domain.api_key)
      newrecord = DropletKit::DomainRecord.new(type: params[:record][:record_type], name: params[:record][:name], data: params[:record][:data],port: params[:record][:port],weight: params[:record][:weight],priority: params[:record][:priority])
      crecord = client.domain_records.create(newrecord, for_domain: params[:domainname])
      if !crecord.id.nil?
        record = domain.records.create(record_type: crecord.type,name: crecord.name,data: crecord.data,port:crecord.port,weight:crecord.weight,priority: crecord.priority,record_id: crecord.id)
        flash[:notice] = "Record Created Successfully"
      else
        flash[:alert] = "Error Occured while saving record"
      end
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        err = $1
        if err.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = err
        end
      end
      flash[:alert] = "Error Occurred while creating Domain Record. #{exception_message}"
    end
    record,crecord,err,exception_message,client = nil
    redirect_to view_domain_path
  end
  def update_record
    begin
      domain = current_user.domains.find_by_name(params[:domainname])
      record = domain.records.find(params[:record][:id])
      client = DropletKit::Client.new(access_token:domain.api_key)
      updaterecord = DropletKit::DomainRecord.new(type: params[:record][:record_type], name: params[:record][:name], data: params[:record][:data],port: params[:record][:port],weight: params[:record][:weight],priority: params[:record][:priority])
      crecord = client.domain_records.update(updaterecord, for_domain: params[:domainname], id: record.record_id)
      record.update_attributes(name: crecord.name,data: crecord.data,port:crecord.port,weight:crecord.weight,priority: crecord.priority)
      flash[:notice] = "Record Updated"
    rescue => e
      if e.message.match(/"message":"(.*)"/)
        if $1.match(/Name Only valid hostname/)
          exception_message = "Only valid hostname characters are allowed. (a-z, a-z, 0-9, ., and -) or a single record of '@'."
        else
          exception_message = $1
        end
      end
      flash[:alert] = "Error occured while updating record. #{exception_message}"
    end
    record,client,updaterecord,crecord,exception_message = nil
    redirect_to view_domain_path
  end

  def delete_record
    begin
      domain = current_user.domains.find_by_name(params[:domainname])
      record = domain.records.find(params[:id])
      client = DropletKit::Client.new(access_token:domain.api_key)
      client.domain_records.delete(for_domain: domain.name, id: record.record_id)
      flash[:notice] = "Record Deleted"
    rescue
      flash[:alert] = "Record Deleted"
    end
    record.destroy
    record,client = nil
    redirect_to view_domain_path
  end
  private
  def domain_params
    params.require(:domain).permit(:name,:ip_address)
  end
  def record_params
   params.require(:record).permit(:record_type,:name,:data,:priority,:port,:weight)
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/domain.html.erb
<% title "Records" %>
<% content_for :head do %>
  <style>
    .add-record{
      margin-top:25px;
    }
    .add-record h3{
      margin-top:40px;
      font-family: 'quicksandregular';
      font-weight: bolder;
    }
    input:not([type=submit]){
      color: #666;
    }
    .update-record input,.update-record .delete-record-button,.update-record .record-type{
      margin:10px !important;
      padding: 0.5em !important;
      font-size: 1.2em !important;
    }
    .update-record .record + .tooltip .tooltip-inner{
      padding:10px 15px;
      font-size:1.2em;
      background-color: rgba(52,52,52, 0.95);
    }
    .record:not(:first-child) > .row{
      margin-top: 20px;
    }
  </style>
  <script>
    function notifyIfBlank(e){
      if(inputVal.length <= 0){
        $.notify({
          message: "Invalid Value For " + errName
        });
        e.preventDefault();
        return true;
      }
      return false;
    }
    function rangeCheck(e,errName,inputObj,minVal,maxVal){
      val = $(inputObj).val();
      if(val < minVal || val > maxVal)  {
        $.notify({
          message: errName + ' must be a number between ' + minVal + ' and ' + maxVal
        });
        e.preventDefault();
      }
    }
    function ipValidator(e,errName,inputObj,ipRegex){
      var ipVal = $(inputObj).val();
      if(!ipRegex.test(ipVal)){
        $.notify({icon:"fa fa-2x fa-exclamation-cirlce",message: "Invalid " + errName});
        e.preventDefault();
      }
    }
    $(document).ready(function(){
      $.notifyDefaults({
        type: "danger"
      });
      $(".update-record input[type=text],.update-record input[type=number]").each(function(){
        toolTipTitle = $(this).attr('placeholder');
        $(this).tooltip({'trigger':'focus','title': toolTipTitle });
      });
      $(document.body).on("click","input[type='submit']",function(e){
        inputsVal = $(this).closest("form").find("input[type=text],input[type=number]");
        $.each(inputsVal,function(){
          inputVal = $(this).val();
          if ($(this).hasClass("name")){
            errName = "Name";
            if(notifyIfBlank(e)){
              return true;
            }
          }
          else{
            //check if val has data
            var entRegex = /^Enter/;
            var extRegex = /^\w+\s(.+)$/;
            var placeholderVal = $(this).attr('placeholder');
            if(entRegex.test(placeholderVal)){
              var match = placeholderVal.match(extRegex);
              errName = match[1];
            }
            else{
              errName = placeholderVal;
            }
            if(notifyIfBlank(e)){
              return true;
            }
          }
          if(errName == "Port")
            rangeCheck(e,errName,this,1,65535);
          else if(errName == "Priority" || errName == "Weight")
            rangeCheck(e,errName,this,0,65535);
          else if(errName == "Hostname" || errName == "Points to"){
            var dotRegex = /\.$/;
            if((!dotRegex.test($(this).val())) && $(this).val() != '@'){
              $.notify({message: errName + " needs to end with a '.'(dot)."});
              e.preventDefault();
            }
          }
          else if(errName == "IP Address"){
            var ipv4Regex = /((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])/;
            ipValidator(e,errName,this,ipv4Regex)
          }
          else if(errName == "IPv6 Address"){
            var ipv6Regex = /(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))/;
            ipValidator(e,errName,this,ipv6Regex);
          }
          else if($(this).hasClass("srv-name")){
            var srvNameRegex = /^\_.+\.\_.+/;
            if(!srvNameRegex.test($(this).val())){
              $.notify({message: "Record name must be in the format of _service._protocol.domain.com"});
              e.preventDefault();
            }
          }
        });


      });
      $('.update-record input').on('keydown',function(){
        $(this).closest("form").find(".update-record-button").removeClass("inactive");
      });
      $('.delete-record-button').click(function(){
        $('.delete-record-button').one('click',function(e) {
          $.notify({message: 'Hang on a second '});
          return false;
        });
      });
      content = $(".detached").remove();
      $(".new-record-types").append(content.find(".a-record"));
      $("input[name='record[record_type]']").click(function(){
        $("label.record-type.new").removeClass("active");
        $(this).parent().addClass("active");
        $(content).append($(".new-record-type").remove());
        $(".new-record-types").html(content.find("." + $(this).parent().attr('id')));
      });
    });
  </script>
<% end %>
<div class="container feature-box" style="text-align: left;">
  <h1 class="domain-title"><%= @domain.name %></h1>
  <div class = "new-record">
		<h2>Add a Record</h2>
    <div class="add-record">
      <h3>Select Record Type</h3>
      <div class="new-record-form">
        <%= simple_form_for(@newrecord,url: add_record_path,method: :post,defaults: {label: false,error_html: { class: 'rederror'}},html:{class: "new-record-form"}) do |f| %>
        <div class="record-types">
          <div class="row">
            <div class="col-md-2" data-toggle="">
              <label class="record-type new a active" id="a-record">
                <%= f.radio_button :record_type, 'A',checked: true%>
                A
              </label>
            </div>
            <div class="col-md-2">
              <label class="record-type new aaaa" id="aaaa-record">
                <%= f.radio_button :record_type, 'AAAA'%>
                AAAA
              </label>
            </div>
            <div class="col-md-2">
              <label class="record-type new cname" id="cname-record">
                <%= f.radio_button :record_type, 'CNAME'%>
                CNAME
              </label>
            </div>
            <div class="col-md-2">
              <label class="record-type new mx" id="mx-record">
                <%= f.radio_button :record_type, 'MX'%>
                MX
              </label>
            </div>
            <div class="col-md-2">
              <label class="record-type new srv" id="srv-record">
                <%= f.radio_button :record_type, 'SRV'%>
                SRV
              </label>
            </div>
            <div class="col-md-2">
              <label class="record-type new txt" id="txt-record">
                <%= f.radio_button :record_type, 'TXT'%>
                TXT
              </label>
            </div>
          </div>
        </div>
          <div class="row new-record-types">
            <div class="detached">
              <div class="new-record-type a-record">
                <div class="col-md-4">
                  <%= f.input_field :name,placeholder: "Enter Name",class: "record name"%>
                </div>
                <div class="col-md-4">
                  <%= f.input_field :data,placeholder: "IP Address",class: "record data"%>
                </div>
                <div class="col-md-4">
                  <%= f.button :submit, "Create A Record",class: "add-record-button"%>
                </div>
              </div>
              <div class="new-record-type aaaa-record">
                <div class="col-md-4">
                  <%= f.input_field :name,placeholder: "Enter Name",class: "record name"%>
                </div>
                <div class="col-md-4">
                  <%= f.input_field :data,placeholder: "IPv6 Address",class: "record data"%>
                </div>
                <div class="col-md-4">
                  <%= f.button :submit, "Create AAAA Record",class: "add-record-button"%>
                </div>
              </div>
              <div class="new-record-type cname-record">
                <div class="col-md-4">
                  <%= f.input_field :name,placeholder: "Enter Name",class: "record name"%>
                </div>
                <div class="col-md-4">
                  <%= f.input_field :data,placeholder: "Points to",class: "record data"%>
                </div>
                <div class="col-md-4">
                  <%= f.button :submit, "Create CNAME Record",class: "add-record-button"%>
                </div>
              </div>
              <div class="new-record-type mx-record">
                <div class="col-md-4">
                  <%= f.input_field :data,placeholder: "Enter Hostname",class: "record data"%>
                </div>
                <div class="col-md-4">
                  <%= f.input_field :priority,placeholder: "Enter Priority",class: "record priority"%>
                </div>
                <div class="col-md-4">
                  <%= f.button :submit, "Create MX Record",class: "add-record-button mx-button"%>
                </div>
              </div>
              <div class="new-record-type txt-record">
                <div class="col-md-4">
                  <%= f.input_field :name,placeholder: "Enter Name",class: "record name"%>
                </div>
                <div class="col-md-4">
                  <%= f.input_field :data,placeholder: "Enter Text",class: "record data"%>
                </div>
                <div class="col-md-4">
                  <%= f.button :submit, "Create TXT Record",class: "add-record-button"%>
                </div>
              </div>
              <div class="new-record-type srv-record">
                <div class="col-md-12">
                  <div class="row">
                  <div class="col-md-4">
                    <%= f.input_field :name,placeholder: "Enter Name",class: "record name srv-name"%>
                  </div>
                  <div class="col-md-4">
                    <%= f.input_field :data,placeholder: "Enter Hostname",class: "record data"%>
                  </div>
                  <div class="col-md-4">
                    <%= f.input_field :priority,placeholder: "Enter Priority",class: "record priority"%>
                  </div>
                  </div>
                  <div class="row">
                    <div class="col-md-4">
                      <%= f.input_field :port,placeholder: "Enter Port",class: "record port"%>
                    </div>
                    <div class="col-md-4">
                      <%= f.input_field :weight,placeholder: "Enter Weight",class: "record weight"%>
                    </div>
                    <div class="col-md-4">
                      <%= f.button :submit, "Create SRV Record",class: "add-record-button srv-button"%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
	</div>
  <% if @records.first.nil? %>
    <h2 class="no-records">This domain has no records !</h2>
  <% else %>
  <div class="records">
    <h2>Current Records</h2>
    <div class="record-list">
      <% @records.each do |record| %>
        <% if !record.nil? %>
          <div class="record">
            <div class="row">
              <%= render partial: "records/shared/#{record.record_type.downcase}",locals: {record: record} %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/records/index.html.erb
<% title "Domains" %>
<% content_for :head do %>
	<script>
		$(document).ready(function(){
			$(".domaintip").tooltip();
			$(".ipaddress").focus(function(){
				$(".instances-dropdown").show();
				$(".invalidip").text("");
			}).focusout(function(){
						window.setTimeout(function(){$(".instances-dropdown").hide();},200);
					});
			$(".domain").focus(function(){$(".invaliddomain").text("");});
			$(".wrapres").click(function(){
				$(".ipaddress").val($(this).children().attr('value'));
			});
			$(".add-domain-submit").click(function(e){
				if(($(".domain").val()).length == 0){
					$(".invaliddomain").text("Invalid Domain");
					e.preventDefault();
				}
				//var ipRegex = /^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$/;
				var ipRegex = /((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])/
				var ipVal = $(".ipaddress").val();
				if(!ipRegex.test(ipVal) || ipVal.length <= 0){
					$(".invalidip").text("Invalid IP Address");
					return false;
				}
			});
		});
	</script>
	<style>
		.invaliddomain,.invalidip{
			font-family: 'quicksandlight';
			font-size:1.4em;
			text-align: left;
		}
		.modal-title,.modal-body p{
			text-align: center;
			font-family: 'quicksandbold'
		}
		.cancel.btn-default,.destroy.btn{
  		width: 100% !important;
			background-color:white;
  	}
		.destroy.btn-primary{
		  color: red !important;
		  outline: 1px solid red !important;
		}
		.destroy.btn-primary:focus,.destroy.btn-primary:hover{
		  background-color: red !important;
		  color: white !important;
			border-color:red !important;
		}
		.commit.destroy.btn-primary{
		  margin-left: 0 !important;
		  margin-top: 5px;
		  border: 1px red solid;
		}
	</style>
<% end %>
<div class="container feature-box" style="text-align:left;">
	<h1 class="domain-title">Domains</h1>
	<div class = "new-domain">
		<h3>Add a Domain</h3>
		<div class="info">
			The specified IP address will be assigned as an A record (for @) for your domain. You can change this later.<span type="button" class="fa fa-question-circle-o domaintip" data-toggle="tooltip" data-placement="top" title="An @ record is the record for the root domain. For example,if you enter domain as 'example.com' and '1.2.3.4' as IP address, then 'http://example.com' will point to '1.2.3.4'"></span>
		</div>
		<div class="add-domain row">
			<%= simple_form_for(@newdomain,:url => domains_path,:method => :post,defaults: {label: false,error_html: { class: 'rederror'}},html: { class: "col-md-12"}) do |f| %>
				<%= f.input_field :name,placeholder: "Domain Name",required:true,:class => "domain" %>
				<div class="instances-list dropdown" style="display:inline-block;">
					<%= f.input_field :ip_address,placeholder: "IP Address",required: true,:class => 'ipaddress'%>
					<div class="instances-dropdown dropdown-menu">
						<% if @instances.blank? %>
							<div class="result noinst">No Instance Found</div>
						<% else %>
							<% Array(@instances).each do |instance| %>
								<div class="wrapres"><div style="cursor:pointer;" class="result inst inst_<%=instance.id%>" value="<%=instance.ip_address%>"><%=instance.name.capitalize%> - <%=instance.ip_address%></div></div>
							<% end %>
						<% end %>
	  			</div>
				</div>
				<%= f.button :submit, "Add Domain",:class => "bluebutton add-domain-submit" %>
			<% end %>
		</div>
		<div class="errors row">
				<div class="rederror col-md-5 invaliddomain"></div>
				<div class="rederror col-md-5 invalidip"></div>
				<div class="col-md-2"></div>
		</div>
	</div>
	<% if @domains.blank? %>
		<h2 class="no-domains"> You haven't added any domains yet! </h2>
	<% else %>
		<div class="domains">
			<h3>Current Domains</h3>
			<div class="domain-list">
				<% Array(@domains).each do |domain| %>
					<div class="domain-record">
						<div class="domain-name"><%= domain.name %></div>
						<div class="domain-button" style="padding-right:0 !important;"><%= link_to "Delete",delete_domain_path(:domainname => domain.name),method: :delete,:class => "delete-domain",title: "Delete this Domain?",data: {:confirm => "This Action is irreversible<br/>All Records Associated with this domain will be deleted too.<br/>Be Certain!"}%></div>
						<div class="domain-button"><%= link_to "Manage",view_domain_path(:domainname=> domain.name),:class => "view-records"%></div>
					</div>
				<% end %>
			</div>
	<% end %>
</div>